os: osx
osx_image: xcode9.2
script:
- make build
- tar czf IntelWifi.tar.gz /Users/travis/Library/Developer/Xcode/DerivedData/IntelWifi-gfhnygtxrrxdvrdpljclrvgbyeiv/Build/Products/Debug/IntelWifi.kext
