os: osx
osx_image: xcode9.2
script:
- make build
- tar czf IntelWifi.tar.gz /Users/travis/Library/Developer/Xcode/DerivedData/IntelWifi-gfhnygtxrrxdvrdpljclrvgbyeiv/Build/Products/Debug/IntelWifi.kext
deploy:
  provider: releases
  api_key:
    secure: Z0htF+6elbHh4kD3FGZpL0I+mAzfEv7yVE4/ljAxNfgE/gSvINfdNHZfjk5dG8X2tw2Zm6VuTAejcQZeW1oadh2mcJgHb/TO/hAcnuXLXYGUNVCn/0cRUQXz7mDeVCeUxzPHWww0ui4BQ72Lgu18OVLnKnznJ3gOF1aR6cXywvI5kf4PPlQhGzvDXSj9yfIvlFhQ2b1yHxSSL9isR4P8Gx2CydSVewzB/nutQw+9DKsbJNpbE/fDioHRlk91SkKD3zoV/cnxlZmd5vaL/PGhco1VY85cfvFSSFe2Y+YZTRRVB1LpfWQMIfnP7GnE9wEFl9UTK5Qr5TIWYYAA2WmeFKPDxX0XaxsmK+ypVdZlPdTi2ckTS/N8SPIPzqNeOLAPbr4hslU12ug/0pkF/Px5E7iAJKWNN0xRG63Nd5gR4qUACC7422JQ91DPx9NZ27L5gMoVKVUQ6aflL1TzauMDgVyvo7EVYQ8+RrC2RrNVwpZe0R1vwAM9HKb6niuo/SJHu/l9haKIryA6UUasKZlfQL6foS/IO6XUZdT3OtBeqD1rN4aus4zA7RZmc8FPYi7RpnGLVkHxYbryZ3TG+dbEH3824BsCMKuKjzWLw71oFNO1OC5TsfR2vKgxd0VM78AuQOlkpt7B4eF8aGppVMT2CROYfZt51bj/s4fHqFrGpG8=
  file: IntelWifi.tar.gz
  on:
    repo: nnn1590/IntelWifi
    branch: travis
